name: solar_anomaly_detection

channels:
  - conda-forge
  - defaults

dependencies:
 - jupyter
 - python=3.9.6
 - click=8.0.1
 - matplotlib=3.4.3
 - numpy=1.21.2
 - pandas=1.3.2
 - scikit-learn=0.24.2
 - tensorflow=2.4.1
 - pytest=6.2.5
